# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15nF29_3LUHCPQoaTGWr1ZnkXOHfEdcN6
"""

class UnittestCarga(unittest.TestCase):

    def test_import_csv_data(self):


        with open('sample_data.csv', 'w') as file:
            file.write("Date,Description,Amount\n")
            file.write("2023-01-01,Income,1000\n")
            file.write("2023-01-02,Expense,-500\n")

        rides = import_csv_data('sample_data.csv')

        self.assertIsNotNone(rides)
        self.assertEqual(len(rides), 2)


if __name__ == '__main__':
    unittest.main()